apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: zipkin-omnition-load
  name: zipkin-omnition-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-omnition-load
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zipkin-omnition-load
    spec:
      containers:
      - image: omnition/synthetic-load-generator:1.0.25
        name: synthetic-load-generator
        env:
        - name: ZIPKINV2_JSON_URL
          value: http://otel-collector:9411/api/v2/spans
        resources: {}
status: {}
